name: data_science

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python=3.12
  - numpy
  - pandas
  - pip
  - requests
  - scikit-learn>=1.6.0
  - spacy>=3.7.0
  - seaborn
  - tqdm
  - pytest
  - pip:
    - colormaps
    - faker
    - gensim>=4.3.3
    - jupyter
    - jupyterlab_myst
    - matplotlib
    - networkx
    - nltk
    - plotly
    - pyvis
    - scipy>=1.8.0
    - umap-learn
