name: deploy-book

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: Tag for manually running the deploy book workflow
        required: true
        default: ''

env:
  BASE_URL: /${{ github.event.repository.name }}

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - name: Set up micromamba
        uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: environment.yml
          cache-environment: true
          cache-downloads: true

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Python info
        run: |
          which python
          python --version
          uv --version

      - name: Install Python dependencies
        run: |
          uv pip sync requirements.txt

      - name: Show installed packages
        run: |
          uv pip list

      - name: Build the book
        run: |
          sphinx-build -E -a -b html . _build/html

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html